### ISSUE TITLE
一个问题

### ISSUE THREAD

**Issue by Damon2019** [QingSimon/licence-plate-recognition#1]
你好，我克隆了您的代码，然后运行surface.py 出现`ValueError: not enough values to unpack (expected 3, got 2)`，图片都没有检测结果，这是什么原因？

**Comment by Damon2019** [comment]
博主，是由于opencv版本的原因，降低版本就行了，谢谢

**Comment by zhx-520** [comment]
您好，请问可以说一下您的版本吗，我用了opencv-python3.4.18.65显示错误

**Comment by zhx-520** [comment]
出现了这个错误：Traceback (most recent call last):
  File "d:\yan1\class\digital_picture\licence-plate-recognition-master\licence-plate-recognition-master\src\surface.py", line 155, in <module>
    surface = Surface(win)
  File "d:\yan1\class\digital_picture\licence-plate-recognition-master\licence-plate-recognition-master\src\surface.py", line 72, in __init__
    self.predictor.train_svm()
  File "d:\yan1\class\digital_picture\licence-plate-recognition-master\licence-plate-recognition-master\src\predict.py", line 196, in train_svm
    self.modelchinese.load("svmchinese.dat")
  File "d:\yan1\class\digital_picture\licence-plate-recognition-master\licence-plate-recognition-master\src\predict.py", line 130, in load
    self.model = self.model.load(fn)
cv2.error: OpenCV(3.4.18) D:\a\opencv-python\opencv-python\opencv\modules\ml\src\svm.cpp:2206: error: (-212:Parsing error) Missing or invalid SVM type in function 'cv::ml::SVMImpl::read_params'
